apiVersion: v1
kind: Service
metadata:
  name: heating-backend-svc
spec:
  selector:
    app: heating-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
